### ISSUE TITLE
Interaction Manager throws Errors in IE if renderer is off-screen

### ISSUE THREAD

**Issue by zOadT** [pixijs/pixi.js#1963]
Hello everyone,

calling the 'getBoundingClientRect' method (InteractionManager.js, line: 332) on an off-screen DOM-Element causes IE to throw an error. All other browsers return a 'ClientRect'-Object with all properties set to 0.

A simple solution would be to check if the 'parentElement' property is null and if so set point.x and point.y to infinity (well, thats what happens in all other browsers :D)

regards zOadT

**Comment by jberube** [comment]
FYI: known IE issue: https://connect.microsoft.com/IE/feedback/details/829392/calling-getboundingclientrect-on-an-html-element-that-has-not-been-added-to-the-dom-causes-unspecified-error

*Closed* as it is fixed in EDGE, but no fix issued on IE <= 11

**Comment by hawk8** [comment]
See my comment in https://github.com/pixijs/pixi.js/issues/1930

For me it seems to be the same issue as this, and it is still an issue as well. I agree with zOadT about how to resolve this.

For us it does not work in IE11 either..

**Comment by ivanpopelyshev** [comment]
That was fixed in pixiv4
