### ISSUE TITLE
3.0.7 - Mismatched anonymous define() with r.js compilation

### ISSUE THREAD

**Issue by TomSlezakowski** [pixijs/pixi.js#2060]
Using pixi (3.0.7) with r.js (2.1.20) produces the following error when running from compiled source ::

<img width="822" alt="screen shot 2015-08-20 at 15 53 00" src="https://cloud.githubusercontent.com/assets/1746136/9397615/7a85f4a2-4753-11e5-96b2-f9e57847740d.png">

<= 3.0.6 works fine.

**Comment by englercj** [comment]
Hmm, not sure what could be causing this. We bumped our browserify version, maybe that is causing it?

https://github.com/pixijs/pixi.js/commit/3dcc484df13930527a455329708c200d4e7b1644

We've updated again since then, do you still get the error if you build the latest dev branch manually?

**Comment by TomSlezakowski** [comment]
Indeed, I pulled down dev and cleaned out the node_modules before rebuilding and still get exactly the same issue :( Struggling to find the exact issue here...

**Comment by englercj** [comment]
Does just downgrading the browserify version to what it was in 3.0.6 solve the problem?

**Comment by GoodBoyDigital** [comment]
Yo! I have had this issue for quite a while - it comes from  a 'define' definition that happens in the async class that gets used. Removing the line fixes the issue. It would be good to figure out a way to fix this properly though.

**Comment by macguffin** [comment]
Haven't checked the code but it can sometimes be fixed simply by naming the define function.
e.g.

 define("foo/title",
        ["my/cart", "my/inventory"],
        function(cart, inventory) {
            //Define foo/title object in here.
       }
    );

http://requirejs.org/docs/errors.html#mismatch

and

http://requirejs.org/docs/api.html#modulename



Cheers

**Comment by GoodBoyDigital** [comment]
this has now been addressed in the latest dev branch 👍

**Comment by TomSlezakowski** [comment]
Still seeing this issue with the latest dev branch, any chance of an update? :)
