### ISSUE TITLE
Interactions v4.1.0

### ISSUE THREAD

**Issue by hendrysadrak** [pixijs/pixi.js#3167]
PIXI 4.1.0 Interactions don't work in Chrome 55.0.2882.0 MacOS Sierra. Works fine in FIrefox. Can't click, though cursor shows as pointer, but on clicking nothing happens. Mouseover and mouseout work fine.

Ex. http://pixijs.github.io/examples/#/demos/interactivity.js even here it doesn't work. No errors.

**Comment by hendrysadrak** [comment]
Updated to Chrome 55.0.2883.18, still doesn't work. Also using PIXI 4.0.3 everything works as expected.

**Comment by hendrysadrak** [comment]
Copied the example from http://pixijs.github.io/examples/#/basics/click.js and made a codepen to log mouse events http://codepen.io/hendrysadrak/pen/JRZmqa

**Comment by hendrysadrak** [comment]
Found a fix, also had to listen for `pointerdown`. So now, for every sprite i want to make clickable on desktop and mobile, i have to listen for `mousedown`, `pointerdown` & `touchdown`? Having 3 lines for a simple click event listening seems excessive.
![image](https://cloud.githubusercontent.com/assets/4000963/19555484/a9707bd0-96c5-11e6-8483-fa69e6a19adf.png)

**Comment by themoonrat** [comment]
if you use pointerdown, you don't need to use mousedown or touchdown at all.

**Comment by Jorisslagter** [comment]
I'd witnessed this same issue my self, trying to updating PIXI 3.10 to PIXI 4.1. But in my opinion it has something to do with the drawing order. Some buttons work normally, but other (maybe because they where drawn later?) don't have the pointer cursor when hovered over with the mouse and don't react to click events.

**Comment by sopilkar** [comment]
Chrome 53.0.2785.143 (64-bit) Mac OS X 10.9.5
Ver 4.1.0
No 'mousedown'/'mouseup' events. 'pointerdown' didn't help.
With ver 4.0.3 it was worked perfect.

Unfortunately we need to roll back to ver. 4.0.3

**Comment by kaansoral** [comment]
This might be related too: https://github.com/pixijs/pixi.js/issues/3158

But I couldn't debug it myself, as it happened to players

My solution was to roll back to 4.0.2, I was on a 4.0.3/dev version (not 4.0.3 release), so the issue I linked was introduced after 4.0.2 - Haven't tried 4.0.3 as I was already occupying the player's time for over an hour by then

**Comment by Excaa** [comment]
Happens also on Chrome canary version 56.0.2900.0 (64-bit), Internet Explorer 11 version 11.321.14393.0 and Edge 38.14393.0.0.

Works on firefox.

**Comment by staff0rd** [comment]
Thought I wasn't seeing this anywhere, turned out I'd just been testing on touch devices only, which are not affected.  Confirmed this fails on Chome Version 55.0.2883.28 beta (64-bit), Win10.

I swapped out all my mouse* and touch* events for pointer* events and this was resolved.

**Comment by englercj** [comment]
Should be fixed now with the merge of #3233.

**Comment by SeminYun** [comment]
this is not resolved..

chrome  56.0.2896. 64-bit is not working with recent version that update on master 2 days ago

**Comment by kaansoral** [comment]
I also reported the same issue, but the update was 4.1.1, it doesn't include the fix yet :(

Have you checked: http://pixijs.download/dev/pixi.js

**Comment by SlavMFM** [comment]
I have version 4.3.2 and facing the same issue. Was it fixed and published or is there any workaround besides reverting to version 4.0.3?

**Comment by guzey** [comment]
In Chrome 62.0.3202.75 "mousedown" works and "pointerdown" doesn't work. Does anybody else have the same issue?

**Comment by ststaynov** [comment]
Same here, any feedback on this?

**Comment by staff0rd** [comment]
Need more information.  I have pointer* events firing fine in Chrome 67.0.3396.79, Windows 10.

**Comment by ststaynov** [comment]
@staff0rd  this is my case. I want to bind an event to the stage so that I make a horizontally draggable website. I figured it would be easier to bind the event on the stage rather than on any other object.
```
this.stage = new PIXI.Container();
stage
          .on('mousedown', onDragStart) // working
          .on('pointerdown', onDragStart); // not working
```

**Comment by staff0rd** [comment]
Looks like i'm getting both here; https://codepen.io/staff0rd/pen/eKGapp?editors=0010, are you not?
