### ISSUE TITLE
no event (mousedown, mouseup, mousemove) will fire on lines (unless their path is opened)

### ISSUE THREAD

**Issue by m-ahmadi** [pixijs/pixi.js#3296]
Here's the thing:

I create a line:

```
new Graphics()
interactive = true
buttonMode = true
beginFill()
lineStyle()
moveTo(50, 50)
lineTo(150, 150)
endFill()
stage.addChild( line )
```

at this point: I can drag the line, but something's not right, cause I can drag the line even If I click not on the line itself, but to the left of it, or to the right. (it's like its path is open or something)

Okey that's not useful, So I try to close the line:
  ```
moveTo(50, 50)
  lineTo(150, 150)
  lineTo(50, 50)
```
But now, Its interactive ness and buttonMode ness is gone.

What's happening here?

**Comment by stbaer** [comment]
This should be fixed in dev by #3165

**Comment by m-ahmadi** [comment]
It says in #3165 that it's fixed. (ivanpopelyshev merged 1 commit into pixijs:dev from stbaer:hit on Oct 20)
 But it still doesn't work, here's an example:
http://codepen.io/mohammad-ahmadi/pen/jVwWLZ

**Comment by m-ahmadi** [comment]
Hello? You there? I'm confused, is it fixed or not?
If not when do you think it's gonna be fixed? @stbaer

**Comment by stbaer** [comment]
Looks like the Polygon.contains bug wasn't the problem here. Afaik you have to define the hitArea for graphics yourself. For a simple rectangular hitArea you could add `line.hitArea = line.getBounds()`.

**Comment by m-ahmadi** [comment]
Thanks for the response, and actually adding `line.hitArea = line.getBounds()` makes it okey.
But (as long as we're talking about it) now the hitArea is a rectangular shape and if you click not on the line itself you can pick the hitArea.

I was just wondering what do you think should I do for that?
(I have a graphing proj, and I use lines for showing links between two nodes, and I want to show an information box popping-up right next to the line when the user clicks on the line)
@stbaer

**Comment by stbaer** [comment]
You can create a Polygon for the hitArea, it does't need to be a Rectangle.

**Comment by stbaer** [comment]
Anyway, @m-ahmadi I think this issue should be closed and questions about how to use pixi asked in the forum.

**Comment by m-ahmadi** [comment]
I don't know, it's your call, If defining a `hitArea `is a normal thing to do, then yes, this isn't an issue.
So I tried to define a Polygon `hitArea `for the line and it worked, and thank you.
But defining a polygon `hitArea` seemed so weird (at least the way I did it).
Here's what I did and it  works perfectly, and again, thank you for telling me, but is all of this a normal thing to do, just so that we can have a straight line that's interactive and can be clicked on?

```
var lineWidth = 10,
    start = {x: 100, y: 100},
    end = {x: 200, y: 100};

line.lineStyle( lineWidth, 0x000000, 1 );
line.moveTo( start.x, start.y );
line.lineTo( end.x, end.y );
line.endFill();

var half = lineWidth / 2;
line.hitArea = new PIXI.Polygon([
  start.x - half, start.y - half,
  start.x + half, start.y + half,
  end.x + half, end.x + half,
  end.x - half, end.x -half
]);
```


But it's not just that.
In general, it seems that the line part of a shape is not considered the shape itself, or something like that, So Let me show you something, and you could tell me If this is something normal or even on purpose or something is wrong with it:
![line-issue1](https://cloud.githubusercontent.com/assets/16363767/20749218/b3163e5c-b706-11e6-801c-fb3e45e3df8f.png)

Remember that I said it's like the line part of a shape is not considered to be the shape itself, (at least in terms of interaction and events being fired on the shape).
Well it's something like that but not entirely true, it's like the lineWidth of the shape gets devided in half, then half of it is clickable and the other half is not. So by setting `alpha = 0.5` it becomes somewhat more clear what's happening:
![line-issue2](https://cloud.githubusercontent.com/assets/16363767/20749402/73907e40-b707-11e6-9347-9a68b55cd66a.png)

**Comment by staff0rd** [comment]
When all other methods of determining a hit (filter, mask, children etc), the `hitArea` is checked if it exists, or if not, `containsPoint` is checked, [see here](https://github.com/pixijs/pixi.js/blob/2057c47c8a9e36e477b1a8a359f87cb4f2f1bcc6/src/interaction/InteractionManager.js#L854-L862).

The issue you're finding without a hitArea is that `containsPoint`, as [seen here](https://github.com/pixijs/pixi.js/blob/2057c47c8a9e36e477b1a8a359f87cb4f2f1bcc6/src/core/graphics/Graphics.js#L848-L874), does not take into account line width, so you're not crazy, but you'll have to specify a hitArea ;)

**Comment by m-ahmadi** [comment]
What about this thing that I said: "lineWidth of the shape gets devided in half, then half of it is clickable and the other half is not"?
Okey lineWidth doesn't get taken into acount, But then why with shapes that have a fill, half of the lineWidth is clickable and half of it is not?
@staff0rd

**Comment by staff0rd** [comment]
The line is centered on the shape's bounds.

**Comment by m-ahmadi** [comment]
How can we define a `hitArea `for a `quadraticCurve` line? is that even possible?
Afaik, you got:
PIXI.Rectangle
PIXI.Circle
PIXI.Polygon
for defining hitArea,
It seems that it's not possible, right?
@staff0rd

**Comment by ivanpopelyshev** [comment]
@m-ahmadi quadraticCurve fills a polygon, right? You can make a graphics, create a curve, then extract the polygon from ".currentPath" property. Please look in the source code of Graphics, I'm too lazy to make a working example for you.

**Comment by m-ahmadi** [comment]
Well I did what you said, and here's what happened:
At first I clicked on the line, and boom! it works!,
But then I noticed that even If I don't click on the line itself, it picks it up:

![untitled](https://cloud.githubusercontent.com/assets/16363767/21027509/4f15aedc-bda6-11e6-9ddf-d2587b648404.png)

I guess the  defined `hitArea `is different than the line itself:

![untitled2](https://cloud.githubusercontent.com/assets/16363767/21027645/001ccfe4-bda7-11e6-9fcc-08e3fb95e08f.png)

I don't know, maybe I did something wrong, But that's not really a clickable curved line.

@ivanpopelyshev

**Comment by qtttttttttting** [comment]
@m-ahmadi Recently, I encountered the same problem and wonder whether you've solve the problem or not. By the way, I do not quite understand your code segment below:
animate();
function animate() {
    requestAnimationFrame(animate);
    renderer.render(stage);
}  
Looking forward for your answers.

**Comment by m-ahmadi** [comment]
@qtttttttttting Since all I wanted was a clickable line, and In my case all the lines would be either straight lines (two points, one starting point, and one ending point) or three point lines. I ended up making a line by using fill, and calculating 4 points from 2 original points and made fill between these 4 points. (not sure this the best algorithm or not :D)

```javascript
var line;
var p = calcPoints({x:100, y:100}, {x:200, y:200}, 2);
var Point = PIXI.Point;

line = new PIXI.Graphics();
line.interactive = true;
line.buttonMode = true;
line.lineStyle(0);

line.beginFill(color);
line.moveTo(p.sLeft.x, p.sLeft.y);
line.lineTo(p.sRight.x, p.sRight.y);
line.lineTo(p.eRight.x, p.eRight.y);
line.lineTo(p.eLeft.x, p.eLeft.y);
line.endFill();
line.alpha = alpha;

function calcPoints(start, end, lineWidth) {
	var half = lineWidth / 2,
		sLeft = {},
		sRight = {},
		eRight = {},
		eLeft = {},
		sX = start.x,
		sY = start.y,
		eX = end.x,
		eY = end.y,
		results = {};

	if ((sX < eX && sY < eY) || // topLeft to bottRight
		(sX > eX && sY > eY)) { // bottRight to topLeft
		sLeft = new Point(sX - half, sY + half);
		sRight = new Point(sX + half, sY - half);
		eRight = new Point(eX + half, eY - half);
		eLeft = new Point(eX - half, eY + half);
	} else if ((sX > eX && sY < eY) || // topRight to bottLeft
		(sX < eX && sY > eY)) { // bottLeft to topRight
		sLeft = new Point(sX - half, sY - half);
		sRight = new Point(sX + half, sY + half);
		eRight = new Point(eX + half, eY + half);
		eLeft = new Point(eX - half, eY - half);
	} else if (sX === eX &&
		(sY > eY || sY < eY)) { // vertical
		sLeft = new Point(sX - half, sY);
		sRight = new Point(sX + half, sY);
		eRight = new Point(eX + half, eY);
		eLeft = new Point(eX - half, eY);

	} else if (sY === eY &&
		(sX < eX || sX > eX)) { // horizontal
		sLeft = new Point(sX, sY + half);
		sRight = new Point(sX, sY - half);
		eRight = new Point(eX, eY - half);
		eLeft = new Point(eX, eY + half);
	}

	results.sLeft = sLeft;
	results.sRight = sRight;
	results.eRight = eRight;
	results.eLeft = eLeft;

	return results;
}
```
And for straight lines, I used this too, I created the line with a sprite by setting the x,y, width/height, and rotation of the sprite. (line2.png is a 1 pixel dot)

```javascript
var lineTexture = new PIXI.Texture.fromImage("images/line2.png");
function newLine(start, end) {
	var sX = start.x,
		sY = start.y,
		eX = end.x,
		eY = end.y,
		pow = Math.pow,
		sqrt = Math.sqrt,
		atan = Math.atan,
		abs = Math.abs,
		PI = Math.PI,
		dx, dy, width, teta;
		
	var s = new PIXI.Sprite(lineTexture);
	s.height = 1;
	dx = abs(eX-sX);
	dy = abs(eY-sY);
	
	if (sY === eY) { // horizontal
		if (sX < eX) {
			s.x = sX;
			s.y = sY;
			s.width = eX-sX;
		} else if (eX < sX) {
			s.x = eX;
			s.y = eY;
			s.width = sX-eX;
		}
	} else if (sX === eX) { // vertical
		if (sY < eY) {
			s.x = sX;
			s.y = sY;
			s.height = eY-sY;
		} else if (eY < sY) {
			s.x = eX;
			s.y = eY;
			s.height = sY-eY;
		}
	} else {
		s.x = sX;
		s.y = sY;
		if (sX < eX && eY > sY) { // to bott right
			s.width = sqrt( pow(dy, 2) + pow(dx, 2) );
			s.rotation = atan(dy / dx);
		} else if (sX < eX && eY < sY) { // to top right
			s.width = sqrt( pow(dy, 2) + pow(dx, 2) );
			s.rotation = -atan(dy / dx);;
		} else if (sX > eX && eY > sY) { // to bott left
			s.width = sqrt( pow(dy, 2) + pow(dx, 2) );
			s.rotation = PI-atan(dy / dx);;
		} else if (sX > eX && eY < sY) { // to top left
			s.width = sqrt( pow(dy, 2) + pow(dx, 2) );
			s.rotation = PI+atan(dy / dx);;
		}
	}
	
	container.addChild(s);
}
```
About the code segment:
the `animate()` function starts the infinite rendering loop, (game loop) and inside it, `requestAnimationFrame()` is called, which asks the browser for the next available frame and executes the callback when that frame is available (and so on, so forth, thus infinite loop).

**Comment by qtttttttttting** [comment]
Thank you for your answer. But in my project, I have to draw curves. Because I need to draw many lines between two points.

**Comment by Christoph** [comment]
I am encountering a similar problem currently. I draw multiple bezier curves in the same area and
and would like to select them. The rectangular hitboxes overlap and I cant click all lines...
How would you solve this?

thanks!
