### ISSUE TITLE
Extras.BitmapText bug with loader path and .fnt files

### ISSUE THREAD

**Issue by artsjedi** [pixijs/pixi.js#3510]
There is an issue when loading BitmapText BitmapText .fnt files when a loader prefix path is specified.

The loader loads the .fnt file at the path specified on the loader. 

for instance: `"myCommonAssetsPath/" + "fonts/myBitmapFont.fnt"`

then makes the bitmap reference inside the .fnt file based on the .fnt file path itsself
for instance: `<page id="0" file="bitmaps/debussy.png"/>` .
it makes `"myCommonAssetsPath/fonts/" + "bitmaps/debussy.png"`

It's ok for now. 

However, later, during loader phase, the assets loader adds the commom prefix **again** using the parseURL() method: for instance 

`"myCommonAssetsPath/" + "myCommonAssetsPath/fonts/bitmaps/debussy.png"`

it means, the default loader path was set twice.

**Comment by ohyou** [comment]
My symptoms:

If you pass a `baseUrl` to the loader, then when it tries to load the picture for a bitmap font, it tries to load it from `www.website.com/path/to/the/game//path/to/the/game/myfont.png` instead of `www.website.com/path/to/the/game/myfont.png`.

My solution:

In class `bitmapFontParser` move line `xmlUrl = xmlUrl.replace(this.baseUrl, '');` to the root scope of the function, so that it executes every time, after the xmlUrl has been loaded, but before the forward slash was added to it.

Hope it helps and gets fixed soon, the bug exists ever since 4.1 I believe.

**Comment by iggyZiggy** [comment]
tried @ohyou solution but it didn't work for me, or i didn't do it right, but pretty much same thing worked:
textureUrl = textureUrl.replace(this.baseUrl, '');

**Comment by artsjedi** [comment]
i'd just made a little hack,, If path starts with "/" then i will just return the path as it is.
Then I made my asset path start with it . ie:  '/myAssets"
```
Loader.prototype._prepareUrl = function (url) {

    if (url.charAt(0) == '/') return url;
```

**Comment by artsjedi** [comment]
OK ! i found a solution, 

In the new version we get this line:

        // absolute url, just use it as is.
        if (parsedUrl.protocol || !parsedUrl.path || url.indexOf('//') === 0) {
            result = url;
        }

which means that you should set your absolute path, or assets path, starting with "//", then it will return the url as is .

**Comment by staff0rd** [comment]
@artsjedi is this resolved now?  Note also #3676 which was recently merged.

**Comment by artsjedi** [comment]
Sorry the problem persist. It still trying to load at assets/assets/debussyBig@0.25x.png. (adding the "asset" path twice)

**Comment by artsjedi** [comment]
I solved the problem by removing the xmlUrl  from

from 
` var textureUrl = xmlUrl + resource.data.getElementsByTagName('page')[0].getAttribute('file');`

to 
` var textureUrl = resource.data.getElementsByTagName('page')[0].getAttribute('file');`
