### ISSUE TITLE
`app.renderer.plugins.prepare.upload` seems does not work

### ISSUE THREAD

**Issue by koalaylj** [pixijs/pixi.js#5856]
### versions:
 * `pixi.js-legacy` :  v5.0.4  Compiled Mon, 24 Jun 2019 18:36:33 UTC
 * `pixi-spine`:  1.5.21
 * `chrome`:  75.0.3770.100  x64
 * `os` :  windows10 pro x64   10.0.18362.175
### question
* ![chrome-performance](https://github.com/koalaylj/data/blob/master/preload-to-gpu.png?raw=true)
what confuse me is why the frame take so long time though i have preloaded the two image to GPU?

##### i have two textures: 
* first texture is spine atlas and preloaded by prepare: `app.renderer.plugins.prepare.upload(resources['sandybeach_atlas_page_sandybeach.png'])`
* sencod texture is loaded by new image().src and preload by prepare : `app.renderer.plugins.prepare.upload( PIXI.Texture.from(img))`

**Comment by themoonrat** [comment]
Could you try the latest dev build of pixi please? I believe I fixed it in this pr: https://github.com/pixijs/pixi.js/pull/5834

**Comment by koalaylj** [comment]
I have tried the latest build `pixi.js-legacy - v5.0.4  Compiled Tue, 02 Jul 2019 03:28:27 UTC`,but still doesnot work.
Is there any way to confirm that the texture have been preloaded to gpu in chrome dev-tools?

**Comment by qtiki** [comment]
I ran into this same issue and I've been debugging it for the whole day. Adding a check for the `glTexture` did indeed fix the exception it was throwing but the upload is still not working.

It seems that the only place where the `texture._glTextures` is initialized is in `TextureSystem.initTexture` which in turn is only called from `TextureSystem.bind`.

Looking at the code for Prepare it would seem that the `uploadBaseTextures` function assumes that the `updateTexture` actually creates the glTexture:
```js
// if the texture already has a GL texture, then the texture has been prepared or rendered
// before now. If the texture changed, then the changer should be calling texture.update() which
// reuploads the texture without need for preparing it again
if (!item._glTextures[renderer.CONTEXT_UID])
{
    renderer.texture.updateTexture(item);
}
```
And then inside `updateTexture` we have an early exit if the glTexture doesn't exist:
```js
updateTexture(texture)
{
    const glTexture = texture._glTextures[this.CONTEXT_UID];

    if (!glTexture)
    {
        return;
    }
    
    ...
```
This doesn't seem right to me.

**Comment by qtiki** [comment]
I did some experimenting and changing the `uploadBaseTextures` to call `renderer.texture.bind(item)` instead of `renderer.texture.updateTexture(item)` seems to fix the gpu uploading. That seems a bit hackyish way to achieve this though so I havent made a PR for this.

**Comment by ivanpopelyshev** [comment]
`updateTexture` was changed in v5, yeah, we need to call `bind` there. @themoonrat

**Comment by qtiki** [comment]
@ivanpopelyshev adding a call to `bind` there will cause an infinite recursion. Guess some other changes are needed too.

**Comment by ivanpopelyshev** [comment]
no, i mean we have to use `bind` in updateBaseTextures , like you've said.

**Comment by qtiki** [comment]
Oh ok. I misunderstood the file/line reference to mean that the bind should be there.

**Comment by qtiki** [comment]
I made a PR for this: https://github.com/pixijs/pixi.js/pull/5874

**Comment by qtiki** [comment]
@koalaylj 
> ##### i have two textures:
> * first texture is spine atlas and preloaded by prepare: `app.renderer.plugins.prepare.upload(resources['sandybeach_atlas_page_sandybeach.png'])`
> * sencod texture is loaded by new image().src and preload by prepare : `app.renderer.plugins.prepare.upload( PIXI.Texture.from(img))`

I've fixed this In the PR but I think you  also have to pass the base texture to upload.

**Comment by themoonrat** [comment]
Closing as fixed in PR mentioned above
